Home page list
yayner2002/js-group-project pull request #23
Opened 2022-05-24 10:27 UTC by medsonmoombe

## The following were implemented in this project 

- Add the home page and added movies cards
- modify the footer and the navigation bar
- Added a module folder and a  JavaScript  file which contains a function that renders the content dynamically

2022-05-24 12:19 UTC, yayner2002 requested changes
Hi, @medsonmoombe  Great job so far. But there are some issues that you have to work on to go to the next exercise 👍

2022-05-24 12:19 UTC, yayner2002 commented on src/modules/showMovies.js
> +    image: '/images/movie1.jpg',
Great job so far. But according to the requirement please use the data that is coming from the API to dynamically render those `images `and `titles `of the movie

2022-05-24 19:36 UTC, medsonmoombe commented
## The following requested changes were implemented
- data  coming from the API dynamically rendered 
-

2022-05-25 06:36 UTC, yayner2002 approved these changes
- Hi, @medsonmoombe  Great job so far. you have done a great job. But here are a few optional issues you have to work on to go to the next project.

2022-05-25 06:42 UTC, yayner2002 commented on src/modules/getdata.js
> +//     main.appendChild(movieDisplay);
Kindly remove unused code from your codebase

2022-05-25 06:42 UTC, yayner2002 approved these changes

2022-05-25 07:44 UTC, medsonmoombe commented on src/modules/showMovies.js
> +    commentBtn.setAttribute('movie-Id', `${data[i].id}`);
Alright @yayner2002  thanks for the review

2022-05-25 07:54 UTC, merged